"""Generate the README showcase figures using the nice-figures style helper.

Run from anywhere:

    python assets/generate_showcase.py

Writes PNGs into this folder. All data below is synthetic, generated with a
fixed seed for reproducibility — these figures exist only to demonstrate the
visual register, not to report any real result.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# Import the style helper straight from the plugin's scripts directory so the
# showcase is generated by exactly the code the plugin ships.
HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(
    0, str(REPO / "plugins/nice-figures/skills/nice-figures/scripts")
)

from soft_style import (  # noqa: E402
    configure_style, figure_title, panel_subtitle, better_badge,
    smooth_curve, rolling_band, rounded_bars, save_figure,
    top_legend, plain_log_ticks, soft_colorbar,
    LINE_PALETTE, BAR_PALETTE, NEUTRAL, CMAP_GRADIENT,
)

configure_style()  # white background, conference-ready


def png_only(fig, name: str) -> None:
    """Save a single PNG into the assets folder (README only needs raster)."""
    save_figure(fig, str(HERE / name), formats=("png",), dpi=200)


# --------------------------------------------------------------------------
# 1. Multi-panel trend with scatter + smoothed line + shaded band (recipe 1)
# --------------------------------------------------------------------------
def fig_training_curves() -> None:
    np.random.seed(0)
    steps = np.linspace(0, 600, 80)
    panels = ["Blackmail", "Financial crimes", "Cancer research"]

    def make_series(start, decay):
        base = start * np.exp(-steps / decay)
        return base + np.random.normal(0, start * 0.15, len(steps))

    # condition -> LINE_PALETTE color, in the canonical palette order
    conditions = {
        "Safety prompt + monitor": "blue",
        "Safety system prompt": "mustard",
        "Generic HHH prompt": "sage",
        "No mitigation": "pink",
    }
    panel_data = {
        "Blackmail": {
            "blue": make_series(0.04, 800), "mustard": make_series(0.10, 400),
            "sage": make_series(0.17, 1200), "pink": make_series(0.18, 600),
        },
        "Financial crimes": {
            "blue": make_series(0.02, 300), "mustard": make_series(0.03, 200),
            "sage": make_series(0.07, 200), "pink": make_series(0.10, 250),
        },
        "Cancer research": {
            "blue": make_series(0.05, 400), "mustard": make_series(0.04, 500),
            "sage": make_series(0.14, 350), "pink": make_series(0.22, 300),
        },
    }

    fig, axes = plt.subplots(1, 3, figsize=(13, 4.5),
                             gridspec_kw=dict(wspace=0.25))
    for ax, panel in zip(axes, panels):
        for color_name, y in panel_data[panel].items():
            c = LINE_PALETTE[color_name]
            xs, lo, hi, _ = rolling_band(steps, y, frac=0.30, k=0.85)
            ax.fill_between(xs, lo, hi, color=c, alpha=0.18, linewidth=0)
            xs2, ys2 = smooth_curve(steps, y, frac=0.30)
            ax.plot(xs2, ys2, color=c, linewidth=2.0)
            ax.scatter(steps, y, color=c, s=8, alpha=0.55, linewidth=0)
        panel_subtitle(ax, panel)
        ax.set_ylim(bottom=0)
        better_badge(ax, direction="down", loc="upper right")

    axes[0].set_ylabel("Rate of misaligned responses")
    fig.text(0.5, -0.02, "RL training steps", ha="center",
             color=NEUTRAL["label"], fontsize=11)

    # One shared legend for all panels, centered between title and subtitles
    handles = [Line2D([0], [0], color=LINE_PALETTE[c], linewidth=2.0, label=l)
               for l, c in conditions.items()]
    top_legend(fig, handles)

    figure_title(fig, "Rate of alignment failures over RL steps", y=1.16)
    png_only(fig, "showcase_training_curves")
    plt.close(fig)


# --------------------------------------------------------------------------
# 2. Grouped rounded bars, three conditions (recipe 4) — the signature look
# --------------------------------------------------------------------------
def fig_grouped_bars() -> None:
    scenarios = ["Blackmail", "Financial crimes", "Cancer research"]
    conditions = ["Baseline", "Constitutional SDF",
                  "Constitutional SDF + stories"]
    colors = [BAR_PALETTE["coral"], BAR_PALETTE["peach"],
              BAR_PALETTE["dark_gray"]]

    means = np.array([
        [0.650, 0.268, 0.181],
        [0.491, 0.111, 0.039],
        [0.673, 0.111, 0.012],
    ])
    errs = np.array([
        [0.018, 0.018, 0.018],
        [0.012, 0.008, 0.005],
        [0.010, 0.010, 0.005],
    ])

    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.set_xlim(-0.5, len(scenarios) - 0.5)  # limits BEFORE rounded_bars
    ax.set_ylim(0, 0.75)

    width = 0.25
    x = np.arange(len(scenarios))
    for i, (col, lab) in enumerate(zip(colors, conditions)):
        offset = (i - 1) * width
        rounded_bars(ax, x + offset, means[:, i], width=width, color=col,
                     radius_frac=0.20, label=lab)
        ax.errorbar(x + offset, means[:, i], yerr=errs[:, i], fmt="none",
                    ecolor=NEUTRAL["ink"], elinewidth=1.1, capsize=3,
                    capthick=1.0, zorder=3)

    ax.set_xticks(x)
    ax.set_xticklabels(scenarios)
    ax.set_ylabel("Misalignment score (lower=better)")
    # Legend above the axes — inside "upper right" would sit on top of the
    # tallest Cancer-research bar
    handles = [Patch(facecolor=c, label=l) for c, l in zip(colors, conditions)]
    top_legend(ax, handles)
    figure_title(fig, "Agentic misalignment evals", y=1.06)
    png_only(fig, "showcase_grouped_bars")
    plt.close(fig)


# --------------------------------------------------------------------------
# 3. Scaling laws, Kaplan/Chinchilla-style: per-run loss curves whose lower
#    envelope traces the compute-efficient frontier (recipe 10)
# --------------------------------------------------------------------------
def fig_scaling() -> None:
    np.random.seed(3)
    import matplotlib as mpl

    # Kaplan-form loss: L(N, D) = (Nc/N)^aN + (Dc/D)^aD, with each run's
    # compute C = 6*N*D. One curve per model size N; the lower envelope of
    # the family is a pure power law in C — the compute-efficient frontier
    # every run curve is tangent to. The data exponent aD is steepened vs.
    # the literal Kaplan fit so each run shows a legible elbow + plateau
    # (with the real ~0.095 the fan is invisibly tight).
    Nc, aN, Dc, aD = 8.8e13, 0.076, 5.0e9, 0.30
    Ns = np.logspace(5, 11, 8)                    # model sizes (params)
    norm = mpl.colors.LogNorm(Ns.min(), Ns.max())

    fig, ax = plt.subplots(figsize=(9, 5.8))
    grids = []
    for N in Ns:
        # Tangency point of this run with the frontier (where d log L / d log D
        # of the run matches the envelope), then sweep 2.5 decades to each
        # side so the run visibly bends away at both ends.
        plateau = (Nc / N) ** aN
        D_star = Dc * ((aN / aD) * plateau) ** (-1.0 / aD)
        D = D_star * np.logspace(-2.5, 1.8, 300)
        C = 6.0 * N * D
        L = plateau + (Dc / D) ** aD
        # light multiplicative noise so curves read as real runs
        L_obs = L * np.exp(np.random.normal(0, 0.004, len(L)))
        ax.plot(C, L_obs, color=CMAP_GRADIENT(norm(N)), linewidth=1.2,
                alpha=0.95, zorder=2)
        grids.append((C, L))

    # Compute-efficient frontier: lower envelope of the (noise-free) family.
    # Fit only where an INTERIOR model is optimal — at the extremes the
    # envelope is biased by the smallest/largest run having no neighbor.
    C_dense = np.logspace(np.log10(min(c.min() for c, _ in grids)),
                          np.log10(max(c.max() for c, _ in grids)), 600)
    losses = np.array([np.interp(C_dense, c, l, left=np.inf, right=np.inf)
                       for c, l in grids])
    env, which = losses.min(axis=0), losses.argmin(axis=0)
    interior = (which > 0) & (which < len(Ns) - 1)
    slope, intercept = np.polyfit(np.log10(C_dense[interior]),
                                  np.log10(env[interior]), 1)
    ax.plot(C_dense, 10**intercept * C_dense**slope, color=NEUTRAL["ink"],
            linestyle="--", linewidth=1.4, zorder=3,
            label=fr"Frontier: $L \propto C^{{{slope:.3f}}}$")

    ax.set_xscale("log")
    ax.set_yscale("log")
    # Loss spans <1 decade: plain numbers beat 2×10⁰-style log labels
    plain_log_ticks(ax, [2, 3, 4, 6, 9])
    ax.set_xlabel("Training compute (FLOPs)")
    ax.set_ylabel("Validation loss")
    ax.legend(loc="upper right")

    soft_colorbar(fig, ax, norm=norm, cmap=CMAP_GRADIENT,
                  label="Model size (parameters)", pad=0.02)

    figure_title(fig, "Loss curves trace the compute-efficient frontier",
                 y=1.00)
    png_only(fig, "showcase_scaling")
    plt.close(fig)


if __name__ == "__main__":
    fig_training_curves()
    fig_grouped_bars()
    fig_scaling()
    print("Done.")
