"""Generate the README showcase figures using the nice-figures style helper.

Run from anywhere:

    python assets/generate_showcase.py

Writes PNGs into this folder. All data below is synthetic, generated with a
fixed seed for reproducibility — these figures exist only to demonstrate the
visual register, not to report any real result.
"""

from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

# Import the style helper straight from the plugin's scripts directory so the
# showcase is generated by exactly the code the plugin ships.
HERE = Path(__file__).resolve().parent
REPO = HERE.parent
sys.path.insert(
    0, str(REPO / "plugins/nice-figures/skills/nice-figures/scripts")
)

from soft_style import (  # noqa: E402
    configure_style, figure_title, panel_subtitle, better_badge,
    smooth_curve, rolling_band, rounded_bars, save_figure,
    LINE_PALETTE, BAR_PALETTE, NEUTRAL,
)

configure_style()  # white background, conference-ready


def png_only(fig, name: str) -> None:
    """Save a single PNG into the assets folder (README only needs raster)."""
    save_figure(fig, str(HERE / name), formats=("png",), dpi=200)


# --------------------------------------------------------------------------
# 1. Multi-panel trend with scatter + smoothed line + shaded band (recipe 1)
# --------------------------------------------------------------------------
def fig_training_curves() -> None:
    np.random.seed(0)
    steps = np.linspace(0, 600, 80)
    panels = ["Blackmail", "Financial crimes", "Cancer research"]

    def make_series(start, decay):
        base = start * np.exp(-steps / decay)
        return base + np.random.normal(0, start * 0.15, len(steps))

    panel_data = {
        "Blackmail": {
            "blue": make_series(0.04, 800), "mustard": make_series(0.10, 400),
            "sage": make_series(0.17, 1200), "pink": make_series(0.18, 600),
        },
        "Financial crimes": {
            "blue": make_series(0.02, 300), "mustard": make_series(0.03, 200),
            "sage": make_series(0.07, 200), "pink": make_series(0.10, 250),
        },
        "Cancer research": {
            "blue": make_series(0.05, 400), "mustard": make_series(0.04, 500),
            "sage": make_series(0.14, 350), "pink": make_series(0.22, 300),
        },
    }

    fig, axes = plt.subplots(1, 3, figsize=(13, 4.5),
                             gridspec_kw=dict(wspace=0.25))
    for ax, panel in zip(axes, panels):
        for color_name, y in panel_data[panel].items():
            c = LINE_PALETTE[color_name]
            xs, lo, hi, _ = rolling_band(steps, y, frac=0.30, k=0.85)
            ax.fill_between(xs, lo, hi, color=c, alpha=0.18, linewidth=0)
            xs2, ys2 = smooth_curve(steps, y, frac=0.30)
            ax.plot(xs2, ys2, color=c, linewidth=2.0)
            ax.scatter(steps, y, color=c, s=8, alpha=0.55, linewidth=0)
        panel_subtitle(ax, panel)
        ax.set_ylim(bottom=0)
        better_badge(ax, direction="down", loc="upper right")

    axes[0].set_ylabel("Rate of misaligned responses")
    fig.text(0.5, -0.02, "RL training steps", ha="center",
             color=NEUTRAL["label"], fontsize=11)
    figure_title(fig, "Rate of alignment failures over RL steps", y=1.04)
    png_only(fig, "showcase_training_curves")
    plt.close(fig)


# --------------------------------------------------------------------------
# 2. Grouped rounded bars, three conditions (recipe 4) — the signature look
# --------------------------------------------------------------------------
def fig_grouped_bars() -> None:
    scenarios = ["Blackmail", "Financial crimes", "Cancer research"]
    conditions = ["Baseline", "Constitutional SDF",
                  "Constitutional SDF + stories"]
    colors = [BAR_PALETTE["coral"], BAR_PALETTE["peach"],
              BAR_PALETTE["dark_gray"]]

    means = np.array([
        [0.650, 0.268, 0.181],
        [0.491, 0.111, 0.039],
        [0.673, 0.111, 0.012],
    ])
    errs = np.array([
        [0.018, 0.018, 0.018],
        [0.012, 0.008, 0.005],
        [0.010, 0.010, 0.005],
    ])

    fig, ax = plt.subplots(figsize=(10, 5.5))
    ax.set_xlim(-0.5, len(scenarios) - 0.5)  # limits BEFORE rounded_bars
    ax.set_ylim(0, 0.75)

    width = 0.25
    x = np.arange(len(scenarios))
    for i, (col, lab) in enumerate(zip(colors, conditions)):
        offset = (i - 1) * width
        rounded_bars(ax, x + offset, means[:, i], width=width, color=col,
                     radius_frac=0.20, label=lab)
        ax.errorbar(x + offset, means[:, i], yerr=errs[:, i], fmt="none",
                    ecolor="#3a3a37", elinewidth=1.1, capsize=3,
                    capthick=1.0, zorder=3)

    ax.set_xticks(x)
    ax.set_xticklabels(scenarios)
    ax.set_ylabel("Misalignment score (lower=better)")
    handles = [Patch(facecolor=c, label=l) for c, l in zip(colors, conditions)]
    ax.legend(handles=handles, loc="upper right")
    figure_title(fig, "Agentic misalignment evals", y=1.00)
    png_only(fig, "showcase_grouped_bars")
    plt.close(fig)


# --------------------------------------------------------------------------
# 3. Scaling-law scatter, log-log + power-law fit (recipe 10)
# --------------------------------------------------------------------------
def fig_scaling() -> None:
    np.random.seed(3)
    # Pure power law L = C0 * C^(-alpha), with C0 pinned by a reference loss
    # at C_ref. Exponents (~0.05-0.06) and the ~8-decade compute sweep match
    # the Kaplan/Chinchilla regime: loss descends from ~5 nats toward the
    # ~1.6-2 nat floor that frontier-scale models reach.
    C_ref = 1e15
    families = {
        "Dense": {"alpha": 0.055, "L_ref": 5.5, "color": LINE_PALETTE["blue"],
                  "compute": np.logspace(15, 22, 8)},
        "MoE":   {"alpha": 0.060, "L_ref": 4.8, "color": LINE_PALETTE["pink"],
                  "compute": np.logspace(15.5, 22.5, 8)},
    }

    fig, ax = plt.subplots(figsize=(8.5, 5.8))
    for name, d in families.items():
        c = d["color"]
        C0 = d["L_ref"] * C_ref ** d["alpha"]
        loss = C0 * d["compute"] ** (-d["alpha"])
        loss_obs = loss * np.exp(np.random.normal(0, 0.02, len(loss)))
        ax.scatter(d["compute"], loss_obs, color=c, s=45, zorder=3,
                   edgecolor="white", linewidth=0.8)
        cf = np.logspace(np.log10(d["compute"].min() * 0.7),
                         np.log10(d["compute"].max() * 1.5), 100)
        ax.plot(cf, C0 * cf ** (-d["alpha"]), color=c, linewidth=1.6,
                alpha=0.85,
                label=fr"{name}: $L \propto C^{{-{d['alpha']:.3f}}}$")

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel("Training compute (FLOPs)")
    ax.set_ylabel("Validation cross-entropy")
    ax.legend(loc="upper right")
    figure_title(fig, "Compute-loss scaling across architectures", y=1.00)
    png_only(fig, "showcase_scaling")
    plt.close(fig)


if __name__ == "__main__":
    fig_training_curves()
    fig_grouped_bars()
    fig_scaling()
    print("Done.")
